spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:C:/data/orders
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:  
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka